/**
 * Intlayer configuration file documentation
 * @see https://intlayer.org/doc/concept/configuration
 */

import type { IntlayerConfig } from "intlayer";

import { Locales } from "intlayer";

const config: IntlayerConfig = {
    internationalization: {
        /**
         * List of supported locales in the application.
         * Default: [Locales.ENGLISH]
         */
        locales: [
            Locales.ENGLISH,
            Locales.CHINESE_HONG_KONG,
        ],

        /**
         * List of required locales that must be defined in every dictionary.
         * If empty, all locales are required in `strict` mode.
         * Default: []
         */
        requiredLocales: [
            Locales.ENGLISH,
            Locales.CHINESE_HONG_KONG,
        ],

        /**
         * Strictness level for internationalized content.
         * - "strict": Errors if any declared locale is missing or undeclared.
         * - "inclusive": Warnings if a declared locale is missing.
         * - "loose": Accepts any existing locale.
         * Default: "inclusive"
         */
        strictMode: "strict",

        /**
         * Default locale used as a fallback if the requested locale is not found.
         */
        defaultLocale: Locales.ENGLISH,
    },
    routing: {
        /**
         * Locale routing strategy.
         * - "prefix-no-default": Prefix all except the default locale (e.g., /dashboard, /fr/dashboard).
         * - "prefix-all": Prefix all locales (e.g., /en/dashboard, /fr/dashboard).
         * - "no-prefix": No locale in the URL.
         * - "search-params": Use ?locale=...
         * Default: "prefix-no-default"
         */
        mode: "no-prefix",

        /**
         * Where to store the user's selected locale.
         * Options: 'cookie', 'localStorage', 'sessionStorage', 'header', or an array of these.
         * Default: ['cookie', 'header']
         */
        storage: [
            "cookie",
        ],
    },
    content: {
        /**
         * File extensions to scan for dictionaries.
         * Default: ['.content.ts', '.content.js', '.content.json', etc.]
         */
        fileExtensions: [
            ".content.ts",
        ],

        /**
         * Directories where .content files are located.
         * Default: ["."]
         */
        contentDir: [
            "./src/locales",
        ],

        /**
         * Directories where source code is located.
         * Used for build optimization and code transformation.
         * Default: ["."]
         */
        codeDir: [
            "./src",
        ],

        /**
         * Command to format newly created <br/> updated .content files.
         */
        formatCommand: 'pnpm exec biome format "{{file}}"',
    },
    compiler: {
        enabled: true,

        /**
         * Defines the output files path for autogenerated content (compiler / autofill / extract)
         *
         * - `./` paths are resolved relative to the component directory.
         * - `/` paths are resolved relative to the project root (`baseDir`).
         *
         * - Including the `{{locale}}` variable in the path will trigger the generation of separate dictionaries per locale.
         *
         * Example:
         * ```ts
         * {
         *   // Create Multilingual .content.ts files close to the component
         *   output: ({ fileName, extension }) => `./${fileName}${extension}`,
         * }
         * ```
         *
         * ```ts
         * {
         *   // Create centralize per-locale JSON at the root of the project
         *   output: ({ key, locale }) => `/locales/${locale}/${key}.content.json`,
         * }
         * ```
         *
         * Variable list:
         *   - `fileName`: The name of the file.
         *   - `key`: The key of the content.
         *   - `locale`: The locale of the content.
         *   - `extension`: The extension of the file.
         *   - `componentFileName`: The name of the component file.
         *   - `componentExtension`: The extension of the component file.
         *   - `format`: The format of the dictionary.
         *   - `componentFormat`: The format of the component dictionary.
         *   - `componentDirPath`: The directory path of the component.
         */
        output: ({ fileName }) => `./${fileName}.content.ts`,

        /**
         * Indicates if the components should be saved after being transformed.
         *
         * - If `true`, the compiler will rewrite the component file in the disk. So the transformation will be permanent, and the compiler will skip the transformation for the next process. That way, the compiler can transform the app, and then it can be removed.
         *
         * - If `false`, the compiler will inject the `useIntlayer()` function call into the code in the build output only, and keep the base codebase intact. The transformation will be done only in memory.
         */
        saveComponents: false,
    },
};

export default config;
